######################################################################
##
## Filename: stopwatch_tb.udo
## Created on: Thu Jul 20 9:35:01 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
