######################################################################
##
## Filename: alarm_no_priority_tb.udo
## Created on: Fri Jul 28 11:25:52 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
