######################################################################
##
## Filename: ink_jet_decoder_tb.udo
## Created on: Fri Jul 28 9:29:49 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
